/**
 * Checks the published surface against the reports checked into `api/`.
 *
 * The canon is `skills/surface/SKILL.md`; this is its executable half.
 *
 * ## Why a file rather than a review
 *
 * A promise is added by writing one line in a barrel, and a reviewer reading a
 * pull request full of implementation sees that line as one more import. The
 * report turns it into its own diff, in a file whose only subject is what the
 * package promises — which is the only form in which a contract change is
 * actually reviewed.
 *
 * ## Two rules
 *
 * 1. **The report matches the barrels.** Regenerate with `--write` and read the
 *    diff; that reading IS the review.
 * 2. **Every facade VALUE appears in a playground scene.** An export nobody has
 *    been shown how to use is a promise made blind, and rule 2 of the canon says
 *    a facade name is never removed — so admission has to cost something.
 *
 * Types are exempt from the second rule: a type is used by using the value it
 * describes, and demanding it be named would push scenes toward annotations
 * nobody writes in real code.
 *
 * Run: node scripts/check-api.mjs [--write]
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { PACKAGES, pkgDir, pkgName } from "./registry.mjs";

/** Where a report lives, by package name. */
/**
 * Where a package's report lives: the bare name, whatever the scope is.
 *
 * Any scope, not one spelled out here. Written as `replace("@lankajs/", "")` it
 * survived the day the scope changed by producing `api/@newscope/host.api.md` —
 * a directory nobody meant, from a gate that reported success.
 */
export const reportPath = (name) => `api/${name.replace(/^@[^/]+\//, "")}.api.md`;

/**
 * Every name a barrel re-exports, with whether it is a value or a type.
 *
 * A barrel re-exports and declares nothing (`skills/structure/SKILL.md`, rule 2),
 * so re-export statements are the whole surface and nothing else has to be
 * parsed. A declaration appearing here would be caught by that rule first.
 */
export const extractExports = (source) => {
	const found = [];

	/*
	 * A published entry is USUALLY a barrel, and was once assumed always to be
	 * one. Five are not: `@lankajs/plugin-prefetch/router` and four subpaths of the
	 * test kit point straight at the unit, because the structure canon wants a
	 * tested unit in its own folder and the subpath a consumer types is shorter
	 * than that folder. Reading only `export { … } from` reported all five as
	 * publishing NOTHING — ten promised names absent from the record whose diff is
	 * the review.
	 */
	for (const match of source.matchAll(
		/^export\s+(?:declare\s+)?(abstract class|class|const|let|var|async function|function|interface|type|enum)\s+([A-Za-z_$][\w$]*)/gm,
	)) {
		found.push({
			name: match[2],
			kind: match[1] === "interface" || match[1] === "type" ? "type" : "value",
		});
	}

	for (const match of source.matchAll(/export\s+(type\s+)?\{([^}]*)\}\s*from/gs)) {
		const isTypeBlock = Boolean(match[1]);

		for (const raw of match[2].split(",")) {
			const clause = raw.trim();
			if (clause.length === 0) continue;

			const isTypeClause = clause.startsWith("type ");
			const name = clause
				.replace(/^type\s+/, "")
				.split(/\s+as\s+/)
				.at(-1)
				.trim();
			if (name.length === 0) continue;

			found.push({ name, kind: isTypeBlock || isTypeClause ? "type" : "value" });
		}
	}

	return found.sort((a, b) => a.name.localeCompare(b.name));
};

/** The report for one package, as it is written to disk. */
export const renderReport = (name, entries) => {
	const lines = [
		`# ${name}`,
		"",
		"Generated by `scripts/check-api.mjs`. Do not edit by hand; run",
		"`node scripts/check-api.mjs --write` and read the diff — that reading is the",
		"review of what this package promises.",
		"",
		"Tiers: `facade` is promised until a major, `extend` may change in a minor,",
		"`internal` in any release. Canon: `skills/surface/SKILL.md`.",
		"",
	];

	for (const entry of entries) {
		lines.push(`## ${entry.subpath}`, "", `Tier: ${entry.tier}`, "");
		if (entry.exports.length === 0) lines.push("_Nothing._", "");
		for (const item of entry.exports) lines.push(`- ${item.kind} \`${item.name}\``);
		lines.push("");
	}

	return lines.join("\n");
};

/** The subpaths of one package, each with its tier and its names. */
export const readSurface = (pkg, root = ".") => {
	const dir = pkgDir(pkg);
	const manifest = JSON.parse(readFileSync(join(root, dir, "package.json"), "utf8"));
	const tiers = new Set(pkg.tiers ?? []);

	return Object.entries(manifest.exports)
		.map(([subpath, target]) => {
			const bare = subpath.replace(/^\.\/?/, "");
			const file = join(root, dir, target);

			return {
				subpath: subpath === "." ? pkgName(pkg) : `${pkgName(pkg)}/${bare}`,
				tier: tiers.has(bare) ? bare : "facade",
				exports: existsSync(file) ? extractExports(readFileSync(file, "utf8")) : [],
			};
		})
		.sort((a, b) => a.subpath.localeCompare(b.subpath));
};

/**
 * Every playground in the repository, concatenated.
 *
 * Every playground, not the package's own: a name used by a SIBLING's playground is
 * demonstrated by an actual consumer, which is stronger evidence than a scene the
 * package wrote about itself. `lankaTestHost` is the worked example — sixteen
 * playgrounds start the framework with it and none of them is its own.
 */
export const playgroundText = (root = ".") => {
	const walk = (current) =>
		readdirSync(current).flatMap((entry) => {
			if (entry === "node_modules" || entry === "dist" || entry === ".git") return [];

			const path = join(current, entry);
			if (statSync(path).isDirectory()) return walk(path);

			// A bench counts as a demonstration too: it uses the published name the
			// way a consumer does and the only difference is that it is timed. The
			// test kit publishes three names whose whole purpose is to be called
			// from one.
			const isDemonstration = path.includes("_playground") || /\.bench\.tsx?$/.test(path);

			return /\.tsx?$/.test(path) && isDemonstration ? [readFileSync(path, "utf8")] : [];
		});

	return walk(root).join("\n");
};

/**
 * Reasons a facade value is not in a scene, shared by the family that shares
 * the reason.
 *
 * Stated once and pointed at, so a family cannot drift into six different
 * excuses for the same fact.
 */
const STUBBED =
	"the playgrounds stub the outside world at exactly this seam, so the real one cannot appear in a scene without the scene stopping being a test";
const A_BASE =
	"the base a published kind already extends; a scene writing one would be writing that kind again";
const BUILT_BY_OWNER =
	"constructed by the plugin that owns it; a scene naming the class would demonstrate construction rather than capability";
const AMBIENT = "the ambient form of something the scenes reach through an instance they hold";
const UNDER_A_DEMONSTRATED_ONE =
	"called by the layer above it on every use, so a scene calling it directly would re-implement that layer";
const CROSSING = "the crossing of two axes each demonstrated on its own";
const THROUGH_CONFIG = "reached through the published config, which is how a consumer uses it";
const HARNESS =
	"part of the harness a scene RUNS INSIDE — a vitest config or a bench file — so a scene using it would be a scene about the test runner";

/**
 * Facade values a playground never uses.
 *
 * A ratchet: entries may leave and none may arrive without a reason. An entry
 * with no reason is a rule opted out of, which is a rule reporting success.
 *
 * It started at 73 the day the check was written. Everything that came off it
 * came off by being demonstrated, and the ones that remain are cases where a
 * scene would show the harness rather than the framework.
 */
export const UNDEMONSTRATED = new Map([
	// The seam every playground replaces: a real fetch, a real EventSource, a real
	// browser storage. A scene using one of these is no longer a test.
	["lanka/gateway:LankaFetchTransport", STUBBED],
	["lanka/gateway:LankaFetchJsonTransport", STUBBED],
	["lanka/gateway:LankaFetchFormDataTransport", STUBBED],
	["@lankajs/storage:LankaCacheStorageAdapter", STUBBED],
	["@lankajs/storage:LankaIndexedDbAdapter", STUBBED],
	["@lankajs/storage:LankaWebStorageAdapter", STUBBED],
	["@lankajs/blob-cache:LankaCacheStorageBlobAdapter", STUBBED],

	// The base every request kind extends: a scene writing one would be writing a
	// request kind, which is what the three published ones already are.
	["lanka/gateway:ALankaRequest", A_BASE],

	// The plugin builds these and hands the scenes the objects, which is what a
	// consumer receives too.
	["@lankajs/plugin-prefetch:LankaChunkPreload", BUILT_BY_OWNER],
	["@lankajs/plugin-prefetch:LankaDataWarmup", BUILT_BY_OWNER],
	["@lankajs/plugin-prefetch:LankaIntentPrefetch", BUILT_BY_OWNER],
	["@lankajs/plugin-sse:createLankaSseTriggerContext", BUILT_BY_OWNER],
	["@lankajs/blob-cache:LankaBlobCacheStore", BUILT_BY_OWNER],
	["@lankajs/blob-cache:createObjectUrlSafely", BUILT_BY_OWNER],
	["@lankajs/blob-cache:revokeObjectUrlSafely", BUILT_BY_OWNER],

	["lanka/gateway:lankaHttpInFlight", AMBIENT],

	["lanka/errors:handleLankaApiError", UNDER_A_DEMONSTRATED_ONE],
	["lanka/logger:LankaLoggerConsoleSink", UNDER_A_DEMONSTRATED_ONE],

	// Lazy is demonstrated, stateless is demonstrated, shared-store is
	// demonstrated. Their pairings add no third behaviour.
	["lanka/viewmodel:createLazyStatelessLankaVM", CROSSING],
	["lanka/viewmodel:createLazySharedStoreLankaVM", CROSSING],

	["@lankajs/tool-eslint:lankaNoUpwardImports", THROUGH_CONFIG],
	["@lankajs/tool-eslint:lankaGatewaysOnlyInViewModels", THROUGH_CONFIG],
	["@lankajs/tool-eslint:lankaDiBarrelsAreFrameworkOnly", THROUGH_CONFIG],
	["@lankajs/tool-eslint:lankaNoGatewayToGateway", THROUGH_CONFIG],
	["@lankajs/tool-eslint:lankaNoViewModelToViewModel", THROUGH_CONFIG],
	["@lankajs/tool-eslint:lankaLayerStyle", THROUGH_CONFIG],

	// Named here the day the record started reading unit-file entries: these four
	// were published all along and reported as nothing. Every one of them is used
	// — by nineteen `vitest.config.ts` files and by every `*.bench.ts` — and none
	// of those is a playground, nor could be.
	["@lankajs/tool-testing/vitest:lankaDiAlias", HARNESS],
	["@lankajs/tool-testing/vitest:LANKA_DI_FIXTURE", HARNESS],
	["@lankajs/tool-testing/lankaBenchCalibration:LANKA_CALIBRATION_NAME", HARNESS],
]);

export const undemonstrated = (surface, text) =>
	surface
		.filter((entry) => entry.tier === "facade")
		.flatMap((entry) =>
			entry.exports
				.filter((item) => item.kind === "value")
				.filter((item) => !new RegExp(`\\b${item.name}\\b`).test(text))
				.map((item) => ({ subpath: entry.subpath, name: item.name })),
		)
		.filter(({ subpath, name }) => !UNDEMONSTRATED.has(`${subpath}:${name}`));

/**
 * Exceptions that are no longer true: the name IS driven by a scene.
 *
 * The list above calls itself a ratchet — "entries may leave and none may arrive
 * without a reason" — and nothing made the leaving happen. An exception that
 * outlives its reason is the quietest way a rule stops applying: the name is
 * demonstrated, the entry says it cannot be, and the next one added beside it
 * inherits the assumption that nobody checks.
 */
export const staleExceptions = (text) =>
	[...UNDEMONSTRATED.keys()].filter((key) =>
		new RegExp(String.raw`\b${key.split(":").pop()}\b`).test(text),
	);

const main = () => {
	const write = process.argv.includes("--write");
	const problems = [];
	mkdirSync("api", { recursive: true });

	// Read once: the corpus is the same for every package.
	const scenes = playgroundText();

	for (const pkg of PACKAGES) {
		const name = pkgName(pkg);
		const surface = readSurface(pkg);
		const report = renderReport(name, surface);
		const path = reportPath(name);

		if (write) {
			writeFileSync(path, report, "utf8");
			continue;
		}

		const current = existsSync(path) ? readFileSync(path, "utf8") : null;
		if (current !== report) {
			problems.push(
				`[report-stale] ${path}\n` +
					"    The barrels and the report disagree. Run `node scripts/check-api.mjs --write`\n" +
					"    and read the diff: a name appearing there is a promise this package will\n" +
					"    keep, and rule 2 of the canon says a facade name is never removed.",
			);
		}

		for (const { subpath, name: exported } of undemonstrated(surface, scenes)) {
			problems.push(
				`[undemonstrated] ${subpath} → ${exported}\n` +
					"    In the facade and used by no playground scene. Show it being used the way\n" +
					"    a consumer would, move it to `extend` until its shape is settled, or add it\n" +
					"    to UNDEMONSTRATED here with the reason the scene is missing.",
			);
		}
	}

	if (write) {
		console.log(`api reports written: ${String(PACKAGES.length)}`);
		return;
	}

	for (const key of staleExceptions(scenes)) {
		problems.push(
			`[stale-exception] ${key}\n` +
				"    Listed as undemonstrated, and a scene drives it. Take the entry out: the\n" +
				"    list is a ratchet, and one that never loosens is one nobody prunes.",
		);
	}

	if (problems.length > 0) {
		console.error(
			`THE SURFACE DIVERGES FROM THE CANON (${String(problems.length)})\n\n` +
				problems.join("\n\n") +
				"\n\nCanon: skills/surface/SKILL.md",
		);
		process.exit(1);
	}

	console.log(`surface follows the canon: ${String(PACKAGES.length)} packages`);
};

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
