/**
 * Every package of the monorepo, one entry each.
 *
 * This is the single source: `package.json`, `tsconfig.json`, `README.md` and the
 * `LICENSE` copy of every package, plus the root README table, are generated from
 * it.
 * Edit here, never the output — `pnpm check:drift` fails when they disagree.
 *
 * `kind` decides the rest: npm name, folder, whether a core peer dependency is
 * required, and how the package is wired.
 */

/**
 * Where this repository lives, and under whose name it publishes.
 *
 * ONE declaration, because it reaches five generated places: every package's
 * `repository` and `homepage`, every plugin manifest, the plugin marketplace,
 * and the provenance block in every shipped skill. Written in five files by
 * hand, it would be wrong in one of them within a month.
 *
 * A placeholder until the first publish: set it to the repository that will own
 * these packages, run `node scripts/scaffold.mjs`, and everything downstream
 * follows. Nothing else in the repository names an owner.
 */
export const ORIGIN = Object.freeze({
	owner: "lankajs",
	repository: "https://github.com/lankajs/lanka",
	/** What `/plugin marketplace add` takes: the repository, without the host. */
	marketplace: "lankajs/lanka",
});

export const KINDS = {
	core: {
		label: "core",
		dir: "core",
		naming: (n) => n,
		badge: "◆",
		rule: "One, unscoped. Everything depends on it; it depends on nothing.",
	},
	module: {
		label: "module",
		dir: "modules",
		naming: (n) => `@lankajs/${n}`,
		badge: "▸",
		rule: "A library in the same box. The app imports and calls it; core does not know it exists.",
	},
	plugin: {
		label: "plugin",
		dir: "plugins",
		naming: (n) => `@lankajs/plugin-${n}`,
		badge: "⬡",
		rule: "A core capability core does not implement itself. Registered with `use()`, then called by core. `peerDependencies: lanka` is mandatory.",
	},
	tool: {
		label: "tool",
		dir: "tools",
		naming: (n) => `@lankajs/tool-${n}`,
		badge: "⚒",
		rule: "Runs before runtime — build, lint, test. Neither module nor plugin.",
	},
};

/**
 * A FAMILY: several packages of one kind that bind the same core port.
 *
 * The only thing allowed to sit directly under a bucket without being a package.
 * Declared here rather than inferred from the path, because every gate that asks
 * "is this directory a package" must get the same answer as the scaffolder, and
 * two readings of one directory tree is how a bucket silently becomes a package.
 *
 * It is not a bucket in the `skills/structure/SKILL.md` sense — those carry an
 * underscore and live inside `src/`. A family is a shelf in a bucket: its members
 * keep their own bare names, their own npm names, and their own versions. Moving
 * a package onto the shelf changes its directory and nothing a consumer can see.
 *
 * The reason for the first one: six of the modules bind `ILankaValidator`, one
 * per schema library. Listed flat they are six of thirteen directories and the
 * relationship is invisible; on a shelf, "what does lanka support" is `ls`.
 *
 * `conformance` names the suite in `@lankajs/tool-testing` that every member
 * answers. It is what lets a shelf hold ONE package: the member is held to a list
 * written independently of it, and the kit's double is the port's second
 * implementation. A shelf of one that names no suite is refused.
 *
 * @type {Array<{ kind: string, slug: string, title: string, gist: string, conformance?: string }>}
 */
export const FAMILIES = [
	{
		kind: "module",
		slug: "validators",
		title: "Validators",
		conformance: "lankaValidatorConformance",
		gist: "One package per schema library, all binding the same port: `ILankaValidator`.",
	},
	{
		kind: "module",
		slug: "storage-adapters",
		title: "Storage adapters",
		gist: "One package per storage engine, all binding the same port: `ILankaStorageAdapter`.",
		conformance: "lankaStorageAdapterConformance",
	},
	{
		kind: "module",
		slug: "query",
		title: "Read caches",
		conformance: "lankaReadCacheConformance",
		gist: "One package per caching library, all binding the same port: `ILankaReadCache`.",
	},
];

/** @type {Array<import("./types").Pkg>} */
export const PACKAGES = [
	// ─────────────────────────────────────────────────────────── CORE ──
	{
		kind: "core",
		slug: "core",
		short: "lanka",
		title: "Core",
		gist: "Fourteen subsystems, two peer dependencies, five extension points.",
		runtime: ["browser", "node", "native"],
		// `@standard-schema/spec` is a TYPES-ONLY package, zero runtime. A regular
		// dependency rather than a peer: the consumer has nothing to do with it.
		deps: { "@standard-schema/spec": "^1.0.0" },
		// Dev-only cycle, deliberate: the test kit needs core, and core's specs need
		// the kit's host stub. The alternative is a copy of `lankaTestHost` in core —
		// two truths about what stands in for a host.
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		peer: { react: "^19.2.0", zustand: "^5.0.10" },
		hasTests: true,
		// Beyond the facade: the two tiers of `skills/surface/SKILL.md`. Reachable,
		// named in the import line, and promising less than a subsystem does.
		tiers: ["extend", "internal"],
		subsystems: [
			"bootstrap",
			"role",
			"config",
			"locator",
			"gateway",
			"validation",
			"cache",
			"storage",
			"mock",
			"errors",
			"scenario",
			"stream",
			"viewmodel",
			"logger",
		],
		notes: [
			"## Which of the three carries a connection",
			"",
			"The framework ships a ViewModel, a scenario and a shared store, and the hardest",
			"question is not how any of them works but which one a connection belongs to. The",
			"ladder, in order — take the first rung that fits and stop:",
			"",
			"1. **One ViewModel owns the state.** Start here always. A screen with a question",
			"   about its own data has no connection to carry.",
			"2. **Another must REACT — a scenario.** It carries a fact (`GapCompleted`), not a",
			"   command, and each side decides what the fact means for its own state. Nobody",
			"   imports anybody: that is the whole reason the layer exists.",
			"3. **Several must CO-EDIT one state — one shared store.** Only when scenarios have",
			"   turned into synchronisation: the same value written in three ViewModels, kept in",
			"   step by hand, racing on a slow answer. Keep the store scoped to the feature and",
			"   give it explicit reset points.",
			"4. **The store became a bus — the feature boundary is wrong.** A shared store that",
			"   everything reads is global state with extra steps. Split the feature and hand",
			"   cross-feature connections back to scenarios.",
			"",
			"The rungs are not styles to pick between. Each costs more than the one above: a",
			"scenario is a name in two files, a shared store is a lifetime somebody has to own.",
			"",
			"`no-viewmodel-to-viewmodel` in `@lankajs/tool-eslint` enforces the only hard part —",
			"that rung 1 never reaches sideways — and the core playground runs rungs 2 and 3",
			"beside each other: a scenario writes into a ViewModel that never heard of the",
			"trigger, and two ViewModels share one selection through `PlaygroundTodoStore`.",
			"",
			"## Naming rule",
			"",
			"**Anything the consumer writes in their own code carries the framework name.**",
			"`ALankaGateway`, `ALankaScenario`, `createLankaVM`, `lankaEventBus`, `LankaLogger`,",
			"`lankaSingletons`.",
			"",
			"Two reasons, the second the stronger one. A reader of an unfamiliar file can see where",
			"`ALankaGateway` came from; `AGateway` says nothing. And the framework does not squat",
			"popular names — `Logger`, `EventBus`, `Storage`, `Singletons`, `Scenarios` are exactly",
			"the names an app wants for ITS own things, and a library that takes them forces the app",
			"to rename.",
			"",
			"`ViewModel` shortens to `VM` in class, factory and type names: `ALankaVM` and",
			"`createLankaVM` are written in every screen file — the same ViewModel reached from",
			"either style, one of the roles `skills/parity/SKILL.md` governs.",
			"",
			"Three names stay bare — `isRecord`, `getStringField`, `generateUuid`. They are pure",
			"utilities over ordinary values; a collision there is resolved at the import site, which",
			"is not available for a class that gets EXTENDED.",
			"",
			"The rule is executed by `core/src/brand.test.ts`, not stated in a document.",
			"",
			"`.lanka_di` barrel names (`Gateways.ts`, `Scenarios.ts`, …) are NOT branded: those files",
			"belong to the consumer and the folder already says whose they are.",
		],
		extensionPoints: [
			["useRequestMiddleware(mw)", "wrap every request", "yes"],
			["inFlight.subscribe(fn)", "observe the number of requests on the wire", "yes"],
			["lankaEventBus.addMiddleware", "intercept bus events, and stop one", "yes"],
			["lankaEventBus.addObserver", "hear what became of each dispatch", "yes"],
			["LankaLogger sinks", "where log output goes", "yes"],
			["use(plugin)", "register a whole plugin", "yes"],
		],
	},

	// ──────────────────────────────────────────────────────── MODULES ──
	{
		kind: "module",
		slug: "storage",
		short: "storage",
		title: "Storage and encryption",
		gist: "Two adapters behind the port, a blob store beside them, WebCrypto encryption, encrypted zustand persistence.",
		// Still browser-only, and `check:runtime` is why: six files name `localStorage`,
		// `caches` or IndexedDB unguarded. The adapters a device needs now exist in
		// `modules/storage-adapters/`, so the remaining work is this package's own —
		// guard the six references, or move the browser adapters behind an entry of
		// their own. Both change what happens when a handler is missing, which is
		// published behaviour and its own change.
		runtime: ["browser"],
		hasTests: true,
		// The test kit, for the yardstick every bench file registers: a value
		// import is a direct dependency, benches included.
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		peer: { zustand: "^5.0.10" },
		contains: [
			"`LankaWebStorageAdapter` — `ILankaStorageAdapter`, both halves",
			"`LankaCacheStorageAdapter` — the same port, asynchronous only",
			"`LankaIndexedDbAdapter` — a different port: `Blob`s for `@lankajs/blob-cache`",
			"`LankaEncryptor` + `WebCryptoSupport` — engine capability detection",
			"`LankaEncryptedStorage`, `LankaEncryptedStateStorage` — zustand persistence",
			"`LankaIdRegistry` — a stored string ↔ short id mapping with persistence hooks",
			"`stringBigIntCodec` — reversible string-to-number encoding, stateless",
		],
		notes: [
			"## Registry, not hasher",
			"",
			"`LankaIdRegistry` does not hash: the id comes from a counter and is STORED, not",
			"computed. Without the stored mapping the number means nothing — which is why the",
			"registry has persistence and a hash could not.",
			"",
			"Reversible string-to-number encoding is a separate, stateless unit (`stringBigIntCodec`).",
			"",
			"## The two ties to core",
			"",
			"`LankaLogger`, for transaction diagnostics, kept deliberately: a private console writer",
			"would mean two log formats in one app.",
			"",
			"And the PORT. `ILankaStorageAdapter` is declared in `lanka/storage` and re-exported here —",
			"an adapter is written against either import and they are the same type. It sits in core so",
			"that `@lankajs/tool-testing`, which depends on `lanka` and nothing else, can hold the",
			"conformance suite every adapter in `modules/storage-adapters/` is measured by.",
			"",
			"No core CONFIG is needed either way — the encryption secret and the legacy plaintext keys",
			"come from the app, so storage works before the framework is bootstrapped.",
		],
	},
	{
		kind: "module",
		slug: "async",
		short: "async",
		title: "Async primitives",
		gist: "Which response may be trusted, and how many requests a burst actually sends.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		deps: { lanka: "workspace:^" },
		contains: [
			"`guard/` — request versioning: a late response learns it lost",
			"`coalescer/` — leading + trailing per key: a burst sends two requests, not a hundred",
			"`safe-fire-and-forget/` — unawaited start whose rejection is not lost in development",
			"`polling/` — interval subscription",
		],
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
	},
	{
		kind: "module",
		slug: "host",
		short: "host",
		title: "Living inside another framework",
		gist: "The two places lanka meets Next, React Router, TanStack Start or Expo: one instance per unit of server work, and one first state per screen.",
		// Two halves in two entries, and the environments are declared per entry:
		// the root is browser code a client component calls, `/server` imports
		// `node:async_hooks`. One entry carrying both would put a node builtin in
		// every browser bundle that tree-shaking failed to reach.
		runtime: ["browser", "node", "native"],
		entries: [{ name: "server", file: "server.ts", runtime: ["node"] }],
		hasTests: true,
		deps: { lanka: "workspace:^" },
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		peer: { zustand: "^5.0.10" },
		contains: [
			"`hydrateLankaVM` — server data as a ViewModel's first state, in the browser",
			"`runLankaRequest` — SSR, RSC, loaders, server functions: an instance per request, carrying the caller's headers",
			"`runLankaStatic` — SSG and ISR: the same scope with identity refused",
		],
		notes: [
			"## Why a package and not a flag on `startLanka`",
			"",
			"`node:async_hooks` exists in node and nowhere else. Core is universal — the browser,",
			"node and React Native — and a single import of a node builtin inside it would put the",
			"filesystem's neighbour in every browser bundle that tree-shaking failed to reach.",
			"",
			"So core publishes a SEAM instead: `setLankaRuntimeResolver` in `lanka/internal`, which",
			'replaces the question "which instance is active" with a strategy. Core ships no',
			"strategy and knows of none; this package installs the one that knows what a request is.",
			"",
			"## One mode per name, because they differ in what may cross in",
			"",
			"`runLankaRequest` is for work with a user waiting — SSR, a server component, a loader,",
			"a server function, a server action, a streamed chunk — and it forwards that user's",
			"`cookie` and `authorization` into the API call. Without that, a signed-in page renders",
			"signed out and flips on hydration, silently.",
			"",
			"`runLankaStatic` is for work with no user: a prerender, a static route, an ISR",
			"revalidation. It refuses headers, in the types and again at runtime, because output",
			"served to everybody must not carry one reader's identity. A boolean flag would have",
			"made that a default somebody flips; a second name makes it hard to write by accident.",
			"",
			"## What still may not cross to the server",
			"",
			"ViewModels. A ViewModel is a zustand store created at module level and read through",
			"React hooks — one store per PROCESS, which on a server is one store shared by every",
			"user connected to it. The gateway layer has no such state, which is exactly why it is",
			"the layer that travels.",
			"",
			"The handoff is data, not state: a loader returns what it fetched, the page passes it as",
			"a prop, and `hydrateLankaVM` makes it the ViewModel's first state in the browser.",
			"",
			"## No cache, deliberately",
			"",
			"Next, React Router and TanStack Start each ship a request cache with revalidation. A",
			"second cache here would disagree with theirs on the first mutation, and the application",
			"would own the disagreement. A gateway returns data; whoever called it decides what to",
			"remember — `revalidate`, `revalidateTag` and their siblings stay the host's.",
		],
	},
	{
		kind: "module",
		slug: "optimistic",
		short: "optimistic",
		title: "Optimistic mutations",
		gist: "Two concurrency strategies with real request cancellation.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		// The test kit, for the yardstick every bench file registers: a value
		// import is a direct dependency, benches included.
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		contains: [
			"`LankaOptimisticActions` — `runLatest` (last click wins) and `runExclusive` (per-item lock)",
		],
		notes: [
			"## Rollback is what separates the two strategies",
			"",
			"`runLatest` does NOT roll back a cancelled request: a fresher click superseded it, and",
			"restoring the previous state would undo what the user just chose.",
			"",
			"`runExclusive` has no superseding click, so it rolls back on ANY failure including",
			"cancellation and timeout. Its lock expires on a timeout for the same reason — a hung",
			"server would otherwise freeze the button forever.",
			"",
			'Cancellation is recognised from `LankaError{kind:"aborted"}`, from `DOMException`, and',
			"from the error name: the framework transport classifies it, but in node `AbortController`",
			"throws a plain `Error`. A missed cancellation costs more than a string comparison.",
		],
	},
	{
		kind: "module",
		slug: "collection",
		short: "collection",
		title: "Lists a screen reads",
		gist: "Sort, filter and paginate on the client without handing React a new array every time.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		// No core dependency: a list does not need a framework. Same evidence as
		// `@lankajs/blob-cache` — a module that works without core is a module.
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		contains: [
			"`createLankaCollectionView` — sort, filter, paginate and stabilise, each memoised on the arguments it was given",
			"`nextLankaSortState` — the header-click cycle: ascending, descending, off",
			"`lankaFilterMatchers` — the ten operators as a table a consumer adds to",
		],
		notes: [
			"## The point is the reference, not the order",
			"",
			"Sorting a list is four lines. What this package is for is what happens next: a new array every render is a new prop for every row, and a screen with two hundred of them repaints because somebody typed into a filter.",
			"",
			"So every operation answers with the array it was GIVEN when nothing changed, and `stabilise` goes further: it reuses the previous object for each row whose contents are equal, so a list that refetched identical data hands React the same items.",
			"",
			"## No inheritance, and no set/get",
			"",
			"The ancestor of this package was one class domains subclassed to override how a value is read and how an operator matches. Both are now parameters: `getValue` and a table of matchers. A protected member is a contract a consumer discovers by breaking (see the structure canon), and neither of these needed to be one.",
			"",
			"The sort cycle is a PURE function of the current state rather than something handed a store's set/get: the ViewModel already owns writing, and a helper that writes for it works with exactly one state library.",
		],
	},
	{
		kind: "module",
		slug: "blob-cache",
		short: "blob-cache",
		title: "Binary resource cache",
		gist: "IndexedDB → Cache Storage → memory → direct fetch, with a memory budget and quota eviction.",
		runtime: ["browser"],
		hasTests: true,
		// NO core dependency, and that is not an accident: the blob cache never calls
		// the framework. A module that works without core is the strongest evidence
		// that it is a module and not a plugin.
		deps: { "@lankajs/storage": "workspace:^" },
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		contains: [
			"`LankaBlobCacheStore` — the IndexedDB → Cache Storage → memory chain, memory budget, quota eviction",
			"`LankaBlobCachePolicy` — resolution without an `<img>` src swap, warm-up queue, fallbacks",
			"`setupLankaBlobCacheLifecycle` — session-end cleanup and object-URL revocation on page hide",
			"`LankaCacheStorageBlobAdapter` — the second rung of the chain",
		],
		notes: [
			"## What the application must declare",
			"",
			"The package caches bytes and refuses to guess whose. Four decisions have no",
			"default that could be right, so each is configuration and each is empty until an",
			"application fills it — spread `LANKA_BLOB_CACHE_CONFIG` and override what you know:",
			"",
			"| Decision | Default | Why there is no better default |",
			"| --- | --- | --- |",
			"| `corsBlockedOrigins` | `[]` | a host whose CORS forbids reading the bytes can never be cached, and trying anyway costs a request per render. Which hosts those are is a property of your infrastructure |",
			"| `sameOriginProxy` | `null` | rewriting a third-party URL through your own origin makes it cacheable. Whether you HAVE such a proxy, and at what path, the package cannot know |",
			"| `acceptContentType` | images | a predicate, not a hard-coded `image/`: an app caching PDFs or fonts changes one function instead of forking the store |",
			"| session end | passed in | `setupLankaBlobCacheLifecycle({ cache, subscribeToSessionEnd })` takes both as parameters. What ENDS a session — a sign-out, a token expiry, a tab closing — is the application's answer, and a module that reached for a locator to find it would stop working without the framework |",
			"",
			"The sizes and lifetimes (`maxTotalBytes`, `maxEntryBytes`, `maxMemoryBytes`,",
			"`ttlMs`, `evictionRatio`, `hydrateLimit`, `maxConcurrent`) do have defaults that are",
			"right for a phone, and are worth revisiting only with a measurement.",
			"",
			"## Safe for content-addressed URLs, and only those",
			"",
			"The cache never revalidates: a key carrying a uuid or a hash cannot go stale, so",
			"there is nothing to check. Point it at a URL whose CONTENT can change under the",
			"same name and it will serve the old bytes until the entry expires — which is not a",
			"bug to be fixed but the property that makes the whole thing cheap.",
		],
	},
	{
		kind: "module",
		slug: "browser",
		short: "browser",
		title: "Platform capabilities",
		gist: "Things with no single API and a fallback for older engines.",
		runtime: ["browser"],
		hasTests: true,
		// The test kit, for the yardstick every bench file registers: a value
		// import is a direct dependency, benches included.
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: {},
		contains: ["`cookies/` — Cookie Store API with a `document.cookie` fallback"],
		notes: [
			"## Why the wrapper exists",
			"",
			"The Cookie Store API is asynchronous and not available everywhere, so a",
			"`document.cookie` fallback is mandatory — the wrapper follows from the platform, not",
			"from taste.",
			"",
			"The bucket grows — network status, tab visibility, storage quota — when a consumer needs",
			"it, not in advance.",
		],
		notes: [
			"## The release guard needs one thing from the application",
			"",
			"`createLankaReleaseGuard` notices that a new build shipped and drops the caches the old one filled — the framework's own among them, since `@lankajs/blob-cache` and the Cache Storage polyfill are what fill them.",
			"",
			"It cannot know what version this build is: that is the bundler's answer, and this package has no bundler. `readVersion` is required and unguessable — with vite it is a fetch of a manifest the build stamps, with a service worker it is the worker, with an env variable it is two words.",
			"",
			"Everything else has a default that can be replaced: where the last seen version is kept (`localStorage`), and what a new release invalidates (every Cache Storage cache).",
			"",
			"It ANSWERS rather than acts. Reloading the page is the commonest response and the worst default: a visitor halfway through a form would lose it.",
		],
	},
	{
		kind: "module",
		family: "validators",
		slug: "zod",
		vendor: "Zod",
		short: "zod",
		title: "zod conveniences",
		gist: "An explicit validator choice: typed helpers plus a bridge for zod 3.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		// The test kit, for the yardstick every bench file registers: a value
		// import is a direct dependency, benches included.
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		peer: { zod: "^4.3.6" },
		contains: [
			"`lankaZodValidator` — core's port under a name that says which library, plus a zod 3 bridge",
			"`TLankaInferred<S>` — schema type inference",
		],
		notes: [
			"## Mapping a server shape is a schema, not an adapter",
			"",
			"A backend whose names are not the application's is read by a TRANSFORMING schema —",
			"`.transform(...)` — because the validator returns what the schema produced. One call",
			"reads the wire and builds the domain object, so there is no adapter layer and no",
			"`adapt()` beside `validate()`.",
			"",
			"Keep the mapping and the domain check as TWO schemas. The first changes when the",
			"server changes, the second when the application does, and each names its own",
			"context — so a failure says which of the two contracts broke, which is the",
			"difference between calling the backend team and reading your own reducer.",
			"",
			"The reverse direction is the same thing: the payload a backend expects back is a",
			"mapping from the domain, not a serialiser. Both are in this package's playground.",
			"",
			"## What this package is for",
			"",
			"zod 4 implements Standard Schema, so there is nothing left to adapt. The package exists",
			"to make the CHOICE explicit: an app installs one validation package — this or",
			"`@lankajs/valibot` — or none, and works with schemas directly.",
			"",
			"What lives here is zod-specific and therefore cannot live in core: typed helpers and",
			"parsing for schemas that do not expose Standard Schema (zod 3). Core knows only the",
			"protocol.",
			"",
			"The symmetry with `@lankajs/valibot` is deliberate: two libraries, two identically shaped",
			"modules, so the difference between them is the difference between the libraries.",
		],
	},
	{
		kind: "module",
		family: "validators",
		slug: "valibot",
		vendor: "Valibot",
		short: "valibot",
		title: "valibot conveniences",
		gist: "The same explicit choice, a different library. Shaped identically to @lankajs/zod on purpose.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		// The test kit, for the yardstick every bench file registers: a value
		// import is a direct dependency, benches included.
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		peer: { valibot: "^1.1.0" },
		contains: [
			"`lankaValibotValidator` — core's port under a name that says which library",
			"`TLankaInferred<S>` — schema type inference",
		],
	},
	{
		kind: "module",
		family: "validators",
		slug: "arktype",
		vendor: "ArkType",
		short: "arktype",
		title: "arktype conveniences",
		gist: "The same explicit choice, a third library. Nothing to adapt: arktype speaks Standard Schema.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		peer: { arktype: "^2.2.3" },
		contains: [
			"`lankaArkTypeValidator` — core's port under a name that says which library",
			"`TLankaInferred<S>` — schema type inference",
		],
	},
	{
		kind: "module",
		family: "validators",
		slug: "yup",
		vendor: "Yup",
		short: "yup",
		title: "yup conveniences",
		gist: "The one package in the family a yup application cannot work without: a synchronous bridge.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		peer: { yup: "^1.7.1" },
		contains: [
			"`lankaYupValidator` — the synchronous bridge, because yup's Standard Schema is async",
			"`TLankaInferred<S>` — schema type inference",
		],
		notes: [
			"## Why this package is not optional",
			"",
			"Every other package in `modules/validators/` exists to make a CHOICE visible: core",
			"already accepts the library's schemas and the package is a name. This one is different.",
			"",
			"yup does implement Standard Schema — since 1.7.x — but its `~standard.validate` is",
			"declared `async` and therefore returns a promise for every schema, valid or not. The",
			"framework's validation port is SYNCHRONOUS and refuses a promise loudly, on purpose: a",
			'port that answered "fine" to a value it never inspected would let unvalidated data',
			"through. So without this package a yup schema cannot be validated by lanka at all —",
			"not slowly, not partially: every call throws.",
			"",
			"The bridge is `validateSync(value, { abortEarly: false })`, which yup has had all",
			"along. It lives here rather than in core for the same reason the zod 3 bridge does:",
			"it is knowledge about a specific library and a specific version, and core knows only",
			"the protocol.",
			"",
			"## What the bridge has to translate",
			"",
			"Three things, each found by a test rather than by reading the documentation:",
			"",
			"- **Paths are bracketed.** yup says `tags[0].id`; `ILankaFieldError.path` is",
			'  segments, so it becomes `["tags", 0, "id"]` and the message string stays',
			"  `tags.0.id: …`, which is how the whole family reads.",
			"- **A top-level failure has no path.** `yup.number().min(18)` refusing `3` reports",
			'  `path: undefined`, which is the form\'s ROOT rather than an input named `""`.',
			"- **An async test cannot run synchronously.** yup throws a plain `Error` saying so.",
			"  Passed through as-is it would reach a consumer as a stray library error; it comes",
			"  back as the port's own loud refusal instead.",
		],
	},
	{
		kind: "module",
		family: "validators",
		slug: "typebox",
		vendor: "TypeBox",
		short: "typebox",
		title: "TypeBox conveniences",
		gist: "A bridge for the one library in the family with no Standard Schema, and a compiled checker it caches.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		peer: { "@sinclair/typebox": "^0.34.52" },
		contains: [
			"`lankaTypeBoxValidator` — the bridge, over a compiled checker cached per schema",
			"`TLankaInferred<S>` — schema type inference",
		],
		notes: [
			"## Why a bridge rather than a name",
			"",
			"TypeBox publishes no `~standard` at all — not asynchronously like yup, not at all —",
			"so core's port cannot be handed a TypeBox schema. The bridge reads",
			"`Value`/`TypeCompiler` and produces the same two lists every package in the family",
			"produces.",
			"",
			"## Why the compiled checker is cached, and why that is not premature",
			"",
			"`TypeCompiler.Compile(schema)` turns a schema into a function, and the function is the",
			"fastest validator in JavaScript. Compilation itself is not fast. Compiling on every",
			"call would make this the SLOWEST package in the family while advertising the",
			"opposite — the exact shape of a claim that measures well in a microbenchmark and",
			"loses in an application.",
			"",
			"So a `WeakMap` keyed by the schema object holds the compiled checker and whether the",
			"schema contains a transform. Weak because the key is the consumer's schema: a strong",
			"map here would keep every schema a screen ever built alive for the life of the tab.",
			"",
			"## Why `Decode` is not simply always called",
			"",
			"`Value.Decode` applies transforms AND re-checks, so calling it after the compiled",
			"check would validate every body twice. `HasTransform` is asked once per schema and",
			"cached beside the checker, so a schema without transforms — which is most of them —",
			"pays for one pass.",
		],
	},
	{
		kind: "module",
		family: "validators",
		slug: "effect",
		vendor: "Effect",
		short: "effect",
		title: "Effect Schema conveniences",
		gist: "Effect keeps its Standard Schema behind a wrapper function; this holds the wrapper still.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		peer: { effect: "^3.22.2" },
		contains: [
			"`lankaEffectValidator` — core's port over `Schema.standardSchemaV1`, cached per schema",
			"`TLankaInferred<S>` — schema type inference",
		],
		notes: [
			"## Why a wrapper rather than a name",
			"",
			"An Effect schema carries no `~standard` of its own. The specification is implemented",
			"by `Schema.standardSchemaV1(schema)`, which BUILDS one — a different object on every",
			"call, measured rather than assumed. Handed straight to the port, every validation",
			"would allocate a wrapper and throw it away, and the schema's own compilation would",
			"happen again with it.",
			"",
			"So the wrapper is cached in a `WeakMap` keyed by the schema. Weak because the key is",
			"the consumer's schema: a strong map would keep every schema a screen ever built alive",
			"for the life of the tab.",
			"",
			"## What is deliberately NOT here",
			"",
			"No Effect runtime, no `Effect.runSync`, no error channel. The package binds one port",
			"and nothing else — an application already using Effect has its own runtime, and a",
			"second one started by a validator is a second one to reason about.",
		],
	},
	{
		kind: "module",
		family: "validators",
		hub: true,
		slug: "any-schema",
		short: "any-schema",
		title: "Any schema, one validator",
		gist: "For the application that ended up with two schema libraries: one validator that routes by dialect.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		// Every validator package and every schema library, as DEV dependencies and
		// nowhere else. The playground is the mixed application this package exists
		// for, and it cannot be written without all of them; the package itself
		// imports none, which is what keeps a consumer from installing six libraries
		// to use one.
		devDeps: {
			"@lankajs/tool-testing": "workspace:^",
			"@lankajs/zod": "workspace:^",
			"@lankajs/valibot": "workspace:^",
			"@lankajs/arktype": "workspace:^",
			"@lankajs/yup": "workspace:^",
			"@lankajs/typebox": "workspace:^",
			"@lankajs/effect": "workspace:^",
			// Not a validator package and never will be: the playground registers it
			// as a CUSTOM dialect, which is the scene that proves an application does
			// not need a release to support a library lanka has never heard of.
			superstruct: "^2.0.2",
		},
		deps: { lanka: "workspace:^" },
		contains: [
			"`createLankaAnySchemaValidator` — one validator over the vendor validators an app installed",
			"`lankaSchemaDialect` — which dialect a schema belongs to, by shape alone",
		],
		notes: [
			"## This is not the recommended way to use lanka",
			"",
			"One application, one schema library. Two means two ways to spell the same rule, two",
			"sets of error messages, and a reviewer who has to know both. The advice in every",
			"other package in this family — install exactly one — still stands.",
			"",
			"It happens anyway: a merger, a team that standardised on something else, a vendored",
			"SDK exporting zod schemas into an application written in Effect. So it is supported,",
			"deliberately and with tests, rather than left to fail in a way nobody predicted.",
			"",
			"## Why a package and not a snippet",
			"",
			"Because the interesting part is the REFUSAL. Each vendor validator now rejects a",
			"schema from another library loudly, which means a gateway holding one validator",
			"cannot serve two libraries — and the obvious workaround, a `try`/`catch` ladder over",
			"all of them, turns a wiring mistake into a value that passed on the third attempt.",
			"",
			"Routing by DIALECT makes the failure land in the right place: a schema whose dialect",
			"nothing was registered for says which package to install, and a schema of no known",
			"dialect says that instead of guessing.",
			"",
			"## It depends on none of the six",
			"",
			"The dialects are told apart by SHAPE — `~standard`, `validateSync`, TypeBox's `Kind`,",
			"Effect's own guard — so this package has no peer dependency on any schema library and",
			"an application pays only for the ones it installed.",
		],
	},

	{
		kind: "module",
		family: "query",
		slug: "tanstack",
		vendor: "Tanstack",
		short: "tanstack-query",
		title: "TanStack Query as a read cache",
		gist: "The recommended member: the only measured library that implements all seven operations.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		// `query-core`, never `react-query`: the peer must not pull React in, or the
		// package stops running in node and the entry needs `"use client"`.
		peer: { "@tanstack/query-core": "^5.102.8" },
		contains: [
			"`LankaTanstackCache` + `createLankaTanstackCache` — `ILankaReadCache` over a `QueryClient`",
		],
		notes: [
			"## Install this only where there is no host cache",
			"",
			"Next, React Router v7 and TanStack Start each carry a request cache and its",
			"revalidation. A second one disagrees with theirs on the first mutation, and the",
			"application owns the disagreement. This package is for the case where the slot is",
			"EMPTY — a plain Vite SPA — not for the case where it is taken.",
			"",
			"## The client is a parameter, never a default",
			"",
			"If anything else in the application reads the same cache — `useQuery` in a component,",
			"devtools — it must be the SAME `QueryClient`. Two of them disagree on the first",
			"mutation, silently, so the constructor refuses to invent one.",
		],
	},
	{
		kind: "module",
		family: "query",
		slug: "nanostores",
		vendor: "Nanostores",
		short: "nanostores-query",
		title: "nanostores as a read cache",
		gist: "For an application already on nanostores: one cache and one subscription model instead of two.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		deps: { lanka: "workspace:^" },
		peer: { "@nanostores/query": "^0.3.4", nanostores: "^1.5.3" },
		contains: [
			"`LankaNanostoresCache` + `createLankaNanostoresCache` — `ILankaReadCache` over `nanoquery()`",
		],
		notes: [
			"## TanStack Query is the default answer; this one has a reason",
			"",
			"Take this member when the application ALREADY uses nanostores for its own state:",
			"then it is one cache rather than two, and one subscription model rather than two.",
			"Take TanStack Query otherwise — it implements all seven operations, this one",
			"implements six.",
			"",
			"## What it cannot do, and why that is honest",
			"",
			"`cancel` is absent. `@nanostores/query` declares its fetcher as",
			"`(...keyParts) => Promise<T>`, so no `AbortSignal` ever reaches the loader — and the",
			"port makes `cancel` optional for exactly this reason. Declaring it as a no-op would",
			"be worse: a ViewModel would believe the request stopped.",
		],
	},

	// ───────────────────────────────────────────── STORAGE ADAPTERS ──
	{
		kind: "module",
		family: "storage-adapters",
		slug: "mmkv",
		vendor: "Mmkv",
		short: "mmkv",
		title: "MMKV as a storage engine",
		gist: "The only engine that fills the synchronous half on a device.",
		runtime: ["native"],
		hasTests: true,
		deps: { lanka: "workspace:^" },
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		// Both majors. v4 moved to Nitro and renamed two methods; v3 is what most
		// applications have installed, and the adapter tells them apart by SHAPE.
		peer: { "react-native-mmkv": ">=3" },
		contains: [
			"`LankaMmkvAdapter`, `createLankaMmkvAdapter` — `ILankaStorageAdapter`, both halves",
			"`ILankaMmkvEngine` — the part of MMKV's surface this uses, as a type",
		],
		notes: [
			"## Why this one first",
			"",
			"MMKV answers without awaiting, and it is the only engine on a device that does. A",
			"persisted store read during the first render either has its value or it does not:",
			"an engine that must be awaited renders once without the value and again with it,",
			"which a user reads as a flash rather than as a load.",
			"",
			"## Two majors, told apart by shape",
			"",
			"v4 moved to Nitro and renamed the constructor (`new MMKV()` → `createMMKV()`) and",
			"the delete (`.delete()` → `.remove()`), and it requires React Native 0.75. v3 is",
			"what most applications have installed today.",
			"",
			"The adapter never constructs the engine, so the constructor's name is the",
			"application's problem and not this package's. What IS this package's problem is the",
			"one method that changed: it asks the instance which it has. A version range would",
			"have been a guess about what the consumer installed; a question to the object is an",
			"answer about what it actually is — the same reasoning `@lankajs/any-schema` uses to",
			"tell schema dialects apart.",
			"",
			"## The engine is handed in, never constructed",
			"",
			"The adapter takes the engine as a parameter — the shape `new LankaWebStorageAdapter(localStorage)`",
			"has had since the beginning — and imports the library nowhere. Three things follow, and the",
			"third is the reason:",
			"",
			"- the package has no runtime dependency on the vendor, so an application pays for what it",
			"  installed and nothing else;",
			"- a second instance with its own namespace is the application's to make, which is what a",
			"  per-tenant store or a test that must not touch the page's keys needs;",
			"- **it is testable off the device.** A native module cannot run in node, so an adapter that",
			"  reached for the library itself could only be tested by the application that shipped it.",
			"  The engine's surface is declared here as a type, and the conformance suite runs against a",
			"  double of it — which is also what proves the declared shape is the shape the library has.",
		],
	},
	{
		kind: "module",
		family: "storage-adapters",
		slug: "react-native-async-storage",
		vendor: "ReactNativeAsyncStorage",
		short: "react-native-async-storage",
		title: "AsyncStorage as a storage engine",
		gist: "The engine an existing application already has installed.",
		runtime: ["native"],
		hasTests: true,
		deps: { lanka: "workspace:^" },
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		peer: { "@react-native-async-storage/async-storage": ">=1.21.0" },
		contains: [
			"`LankaReactNativeAsyncStorageAdapter`, `createLankaReactNativeAsyncStorageAdapter` — the port, asynchronous only",
			"`ILankaReactNativeAsyncStorageEngine` — the part of AsyncStorage's surface this uses",
		],
		notes: [
			"## Why the long name",
			"",
			"The port's asynchronous half is `ILankaAsyncStorageAdapter`, and a class called",
			"`LankaAsyncStorageAdapter` beside it would read as that interface's implementation",
			"rather than as a binding of one library. The names differ by an `I` and mean",
			"different things, which is the collision worth paying four syllables to avoid.",
			"",
			"The package binds `@react-native-async-storage/async-storage` and is named after it.",
			"",
			"## What it does not do",
			"",
			"`clear()` empties the WHOLE store, because AsyncStorage's does: the library has one",
			"space per application and no namespaces. An application keeping two spaces gives",
			"each its own key prefix and its own adapter, or uses an engine that has namespaces.",
			"That is a property of the library, stated here rather than hidden behind a",
			"key-prefix option this package would then have to be trusted about.",
			"",
			"## The engine is handed in, never constructed",
			"",
			"The adapter takes the engine as a parameter — the shape `new LankaWebStorageAdapter(localStorage)`",
			"has had since the beginning — and imports the library nowhere. Three things follow, and the",
			"third is the reason:",
			"",
			"- the package has no runtime dependency on the vendor, so an application pays for what it",
			"  installed and nothing else;",
			"- a second instance with its own namespace is the application's to make, which is what a",
			"  per-tenant store or a test that must not touch the page's keys needs;",
			"- **it is testable off the device.** A native module cannot run in node, so an adapter that",
			"  reached for the library itself could only be tested by the application that shipped it.",
			"  The engine's surface is declared here as a type, and the conformance suite runs against a",
			"  double of it — which is also what proves the declared shape is the shape the library has.",
		],
	},
	{
		kind: "module",
		family: "storage-adapters",
		slug: "secure-store",
		vendor: "SecureStore",
		short: "secure-store",
		title: "The keychain as a storage engine",
		gist: "The one that bends the port: no wipe, no enumeration, two kilobytes, and a restricted key.",
		runtime: ["native"],
		hasTests: true,
		deps: { lanka: "workspace:^" },
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		peer: { "expo-secure-store": ">=12" },
		contains: [
			"`LankaSecureStoreAdapter`, `createLankaSecureStoreAdapter` — the port over the keychain",
			"`ILankaSecureStoreEngine` — the three calls `expo-secure-store` publishes",
		],
		notes: [
			"## Three clauses this engine cannot keep by itself",
			"",
			"`expo-secure-store` deletes a key it is handed and offers nothing else. No wipe, no",
			"list of what it holds, keys limited to letters, digits, `.`, `-` and `_`, and values",
			"of roughly two kilobytes. The port asks for more than that, and the adapter is where",
			"the difference is paid rather than in every caller:",
			"",
			"| Clause | What this adapter does |",
			"| --- | --- |",
			"| 5, 7 — `clear()` empties what was written | keeps an INDEX of its own keys, and wipes by walking it |",
			"| 6 — `keys()` answers what was written | the index again, so the answer is the namespace's and not the keychain's |",
			"| 11 — a key is used as given | encodes on the way in and DECODES on the way out, so a caller never sees a key it did not write |",
			"| 10 — a value the engine cannot hold fails | refuses over the ceiling instead of letting the platform truncate |",
			"",
			"The index is a row in the keychain like any other, under a key of this package's own.",
			"It is written on every set and remove, which is one extra write per operation — the",
			"price of `clear()` being true. An engine that could enumerate would not pay it, and",
			"none of the others do.",
			"",
			"## Why the ceiling is refused rather than split",
			"",
			"Splitting a large value across rows would make this package a filesystem with a",
			"keychain underneath, and the failure it hides is worse than the one it prevents: half",
			"a token read back as a whole one. A session token fits in two kilobytes; a value that",
			"does not is a value that does not belong in a keychain.",
			"",
			"## The engine is handed in, never constructed",
			"",
			"The adapter takes the engine as a parameter — the shape `new LankaWebStorageAdapter(localStorage)`",
			"has had since the beginning — and imports the library nowhere. Three things follow, and the",
			"third is the reason:",
			"",
			"- the package has no runtime dependency on the vendor, so an application pays for what it",
			"  installed and nothing else;",
			"- a second instance with its own namespace is the application's to make, which is what a",
			"  per-tenant store or a test that must not touch the page's keys needs;",
			"- **it is testable off the device.** A native module cannot run in node, so an adapter that",
			"  reached for the library itself could only be tested by the application that shipped it.",
			"  The engine's surface is declared here as a type, and the conformance suite runs against a",
			"  double of it — which is also what proves the declared shape is the shape the library has.",
		],
	},
	{
		kind: "module",
		family: "storage-adapters",
		slug: "unstorage",
		vendor: "Unstorage",
		short: "unstorage",
		title: "Twenty drivers as one storage engine",
		gist: "The server, the edge, and every engine this repository has never heard of.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		deps: { lanka: "workspace:^" },
		// The one engine of the four that runs in node, so the playground drives the
		// REAL library rather than a double of it — which is what proves the shape
		// declared here is the shape unstorage has.
		devDeps: { "@lankajs/tool-testing": "workspace:^", unstorage: "^1.17.5" },
		peer: { unstorage: "^1.17.5" },
		contains: [
			"`LankaUnstorageAdapter`, `createLankaUnstorageAdapter` — the port over any unstorage driver",
			"`ILankaUnstorageEngine` — the part of unstorage's surface this uses",
		],
		notes: [
			"## What this is for",
			"",
			"The other three members are one engine each. This one is twenty-odd: a filesystem, a",
			"Redis, a Cloudflare KV, a Vercel KV, a Netlify blob store, a Mongo, an SQL table, a",
			"Capacitor preference store, the browser's own. An application whose engine this",
			"repository has never heard of writes an unstorage driver and keeps the port.",
			"",
			"It is also the member that makes `@lankajs/host/server` able to persist anything at",
			"all: the other three are native modules.",
			"",
			"## Raw in, raw out",
			"",
			"unstorage deserialises by default — its `getItem` parses what looks like JSON, so a",
			'stored `"null"` comes back as `null` and `"{}"` as an object. Clause 1 of the port',
			"says a value returns byte for byte, so this adapter uses the raw pair. It is one",
			"character in the method name and the whole difference between a string store and a",
			"document store.",
			"",
			"## The engine is handed in, never constructed",
			"",
			"The adapter takes the engine as a parameter — the shape `new LankaWebStorageAdapter(localStorage)`",
			"has had since the beginning — and imports the library nowhere. Three things follow, and the",
			"third is the reason:",
			"",
			"- the package has no runtime dependency on the vendor, so an application pays for what it",
			"  installed and nothing else;",
			"- a second instance with its own namespace is the application's to make, which is what a",
			"  per-tenant store or a test that must not touch the page's keys needs;",
			"- **it is testable off the device.** A native module cannot run in node, so an adapter that",
			"  reached for the library itself could only be tested by the application that shipped it.",
			"  The engine's surface is declared here as a type, and the conformance suite runs against a",
			"  double of it — which is also what proves the declared shape is the shape the library has.",
		],
	},

	// ──────────────────────────────────────────────────────── PLUGINS ──
	{
		kind: "plugin",
		slug: "http",
		short: "http",
		title: "Request policy",
		gist: "Retry, idempotency, CSRF, credentials, auth refresh and timeout as request middleware.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		socket: "ALankaRequest → middleware chain (`useRequestMiddleware`), wired through `lanka.use()`",
		notes: [
			"## Mapping a server shape is a schema, not an adapter",
			"",
			"A backend whose names are not the application's is read by a TRANSFORMING schema —",
			"`v.pipe(..., v.transform(...))` — because the validator returns what the schema produced. One call",
			"reads the wire and builds the domain object, so there is no adapter layer and no",
			"`adapt()` beside `validate()`.",
			"",
			"Keep the mapping and the domain check as TWO schemas. The first changes when the",
			"server changes, the second when the application does, and each names its own",
			"context — so a failure says which of the two contracts broke, which is the",
			"difference between calling the backend team and reading your own reducer.",
			"",
			"The reverse direction is the same thing: the payload a backend expects back is a",
			"mapping from the domain, not a serialiser. Both are in this package's playground.",
			"",
			"## Differences are CONFIGURATION, never a branch",
			"",
			"Two apps can need genuinely different request policies — cookie session versus token",
			"session, CSRF or none, retry or none. A plugin expressing one of them as `if (console)`",
			"would only move the fork to another file; this package names no consumer.",
			"",
			"## Three rules, each of which cost a defect",
			"",
			"**Retry without idempotency is more dangerous than no retry.** A failure can happen",
			"AFTER the server performed the request: the response was lost, the action happened. A",
			"retry without a key reads as a new intent and creates a second object — a payment, an",
			"invitation. So this configuration is rejected AT BUILD TIME, not on the first retry in",
			"production.",
			"",
			"**A key is issued once per intent, never per attempt.** Idempotency registers OUTSIDE",
			"retry for exactly this reason: inside, it would mint a new key per attempt — the very",
			"defect the key exists to prevent.",
			"",
			"**Auth refresh takes a function, not an endpoint URL.** A plugin that knew the endpoint",
			"would also know the response shape and the session storage, and would stop being a",
			"request policy. One attempt per 401: a second 401 after a successful refresh means",
			"refresh does not work and the loop must break — in production an infinite loop looks",
			"like a hung interface, not like an error.",
			"",
			"## A cookie session has to send the cookie",
			"",
			'`credentials` lives in `defaults`, and `lankaCookieSessionPolicy` sets `"include"`. The',
			"preset used to set the CSRF header and leave the credential alone — a proof of origin",
			"attached to a request that authenticated nobody, because `fetch` defaults to",
			'`"same-origin"` and the ordinary deployment puts the API on another host. There was',
			"nowhere else to say it: core knows nothing of cookies on purpose, so an application",
			"wrote the line into a transport of its own and, having written a transport, put the",
			"base URL, the retry and the refresh in there too.",
		],
	},
	{
		kind: "plugin",
		slug: "sse",
		short: "sse",
		title: "Server-sent events as a source of change",
		gist: 'SSE transport, bridges into scenarios, and a "came from outside" marker for mutations.',
		runtime: ["browser", "node", "native"],
		hasTests: true,
		socket: "use(plugin) · host.apiBaseUrl",
		deps: { "@lankajs/async": "workspace:^" },
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		contains: [
			"`LankaSseTransport` — connection, reconnection with growing backoff, envelope parsing",
			"`ALankaSseBridge` — the shape of a server-event → scenario bridge, from `lanka/stream`",
			'`createLankaSseTriggerContext` — the "came from outside" marker, from `lanka/stream`',
			"re-export of the guard and coalescer from `@lankajs/async`",
		],
		notes: [
			"## No `EventSource` is not a failure",
			"",
			"On an engine without server events the plugin is simply off for the session: every",
			"screen keeps working because the same data arrives through route loaders. The app",
			"updates on navigation instead of instantly. This is a PROMISE the product relies on,",
			"not an implementation detail.",
			"",
			"The same principle one rung down: some engines expose the constructor but refuse the",
			"connection (scheme, proxy, strict CSP). There the plugin gives up quietly instead of",
			"entering a reconnect loop — retrying what cannot succeed is a storm.",
			"",
			'## The "came from outside" marker',
			"",
			"A handler that updates state cannot tell its own change from someone else's: the user",
			"pressed a button and then receives the server event about that button. Without the",
			"marker the screen notifies the user about their own action, and an optimistic update is",
			'rolled back by a "foreign" response that in fact confirms it.',
			"",
			"The marker lives on the plugin INSTANCE, not in the module: two framework instances (a",
			"test beside the app) would share a module-level flag, and one instance's handler would",
			"see a marker set by the other.",
			"",
			"Concrete bridges do NOT belong here: which events exist is the app's domain.",
			"",
			"## Only the connection is about SSE",
			"",
			"The bridge, the marker and the plugin's lifetime are `lanka/stream`'s, shared with",
			"`@lankajs/plugin-websocket`, `@lankajs/plugin-graphql` and `@lankajs/plugin-grpc`. They",
			"are re-exported here under the names this package published first, so an application on",
			"SSE needs one import and one that swaps the wire changes a line of configuration rather",
			"than every bridge file.",
		],
	},
	{
		kind: "plugin",
		slug: "websocket",
		short: "websocket",
		title: "A two-way channel as a source of change",
		gist: "A WebSocket behind the same port SSE uses, plus the half SSE does not have: sending.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		socket: "use(plugin) · host.apiBaseUrl",
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		contains: [
			"`LankaWebSocketTransport` — connection, heartbeat, outbox, reconnection with growing backoff",
			"`ILankaWebSocketChannel` — the port: the event transport, plus `send`",
			"`lankaWebSocket` — the plugin: bridges attached, lifetime owned, marker set",
		],
		notes: [
			"## The same port, so the choice is not permanent",
			"",
			"`LankaWebSocketTransport` implements `ILankaServerEventTransport` from `lanka/stream`,",
			"which is what `@lankajs/plugin-sse` takes as its `transport`. An application that",
			"started on SSE and hit a proxy stripping `text/event-stream` changes one line of",
			"configuration; every bridge, scenario and screen above it is untouched. That is the",
			"promise the port was written for, and this package is the first thing to keep it.",
			"",
			"## Sending is not a bridge's job",
			"",
			"A bridge is inbound only, on a two-way wire as much as on a one-way one. A bridge that",
			"also sends is the one object that both starts and finishes a conversation: untestable",
			"without a socket, and the place every screen eventually reaches into. `plugin.socket` is",
			"the channel, and it goes to whatever already owns the action — a gateway, a ViewModel.",
			"",
			"## What the outbox is for, and what it is not",
			"",
			"A message sent while the link is down is held and flushed when it opens, because a",
			"reconnect is invisible from a screen and losing the click that happened during one is",
			"not a behaviour anybody chose. The buffer is BOUNDED and drops its oldest entry: an",
			"unbounded outbox on a connection that never comes back is a memory leak that looks like",
			"patience. `queueWhileClosed: false` turns it off for a wire where a late message is",
			"worse than none.",
			"",
			"## A dead socket does not report itself",
			"",
			"A half-open connection — the peer gone, the socket still `OPEN` — is the failure a",
			"WebSocket has and SSE does not. `heartbeatMs` sends a ping and expects an answer inside",
			"`heartbeatTimeoutMs`; silence is treated as a drop and enters the same reconnect ladder.",
			"Off by default: a heartbeat against a server that does not answer pings would close a",
			"connection that works.",
			"",
			"## The envelope is a seam, not a format",
			"",
			"A WebSocket has no per-event channel, so the event type is read out of the frame:",
			"`{ type, payload }` and `{ type, ...fields }` are both understood. `readFrame` and",
			"`writeFrame` replace that wholesale for a backend whose protocol was decided before",
			"this package existed.",
		],
	},
	{
		kind: "plugin",
		slug: "graphql",
		short: "graphql",
		title: "GraphQL: operations, and subscriptions",
		gist: "A request kind that reads the errors array, a gateway that writes query and mutate, and graphql-ws as a stream.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		socket: "use(plugin) · host.apiBaseUrl",
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		contains: [
			"`LankaGraphqlRequest` — a request kind: one POST, and `errors` read as a tagged failure",
			"`ALankaGraphqlGateway` / `createLankaGraphqlGateway` — `query` and `mutate`, both styles",
			"`LankaGraphqlSubscriptionTransport` — the `graphql-ws` protocol as a stream transport",
			"`lankaGraphql` — the plugin, for subscriptions only",
		],
		notes: [
			"## The one thing this package is really for",
			"",
			"**GraphQL answers `200 OK` with an `errors` array.** Through an ordinary JSON request",
			"that is a success carrying a body the screen then has to inspect — so every application",
			"grows the same helper, and the ones that forget show a spinner over a failed mutation.",
			'`LankaGraphqlRequest` turns it into `LankaError` with `kind: "domain"`, which is the kind',
			"the framework already has for a server refusing deliberately and naming the reason.",
			"",
			"An `errors` array beside non-null `data` is a PARTIAL result and is not a failure: the",
			"data is returned and the errors are handed to `onPartialErrors`. Refusing it would throw",
			"away a page that rendered because one nullable field did not.",
			"",
			"## Two halves, used apart",
			"",
			"Operations need no plugin: build a gateway on `ALankaGraphqlGateway`, or hand",
			"`createLankaGraphqlRequest()` to any gateway you already have. `lanka.use(...)` is for",
			"SUBSCRIPTIONS, because a subscription is a connection and a connection needs a lifetime",
			"to belong to.",
			"",
			"## No document parsing, ever",
			"",
			"A document is a string, and `TypedDocumentNode` from a code generator is accepted by",
			"reading its `loc.source.body`. The package never parses GraphQL: doing so would mean",
			"shipping a parser, and a build-time code generator already knows more about the schema",
			"than a runtime parser can.",
			"",
			"## Subscriptions are one operation per event type",
			"",
			"`graphql-ws` multiplexes by an id per subscription; this maps each to a named event a",
			"bridge already understands, so a subscription and a server-sent event reach a scenario",
			"through exactly the same code. The socket is opened once and `subscribe` is sent per",
			"type — including again after a reconnect, which the far end has forgotten about.",
		],
	},
	{
		kind: "plugin",
		slug: "grpc",
		short: "grpc",
		title: "gRPC-Web: unary calls and server streams",
		gist: "The framing, the trailers and the status codes — with the message codec left to whoever generated it.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		socket: "use(plugin) · host.apiBaseUrl",
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		contains: [
			"`ILankaGrpcCodec` — the seam: encode a request, decode a response",
			"`LankaGrpcRequest` — gRPC-Web framing, trailers, `grpc-status` as a tagged failure",
			"`ALankaGrpcGateway` / `createLankaGrpcGateway` — `unary`, both styles",
			"`LankaGrpcStreamTransport` — a server stream read as named events",
		],
		notes: [
			"## The package does not know protobuf, and must not",
			"",
			"A message codec belongs to whatever generated the message types — `protobuf-es`,",
			"`ts-proto`, a hand-written one. Shipping a runtime for one of them would pick the",
			"consumer's code generator for them and add a dependency to everyone who chose",
			"differently. `ILankaGrpcCodec` is two functions, and `createLankaGrpcJsonCodec()` is the",
			"one this package ships — for a server speaking `+json`, and for a test that wants to",
			"read what went over the wire.",
			"",
			"## What is here is the part everyone rewrites",
			"",
			"The length-prefixed framing, the trailers frame, and the mapping from `grpc-status` to a",
			"failure the application can branch on. Sixteen status codes become five kinds:",
			"`CANCELLED` is `aborted` and is not shown, `DEADLINE_EXCEEDED` is `timeout`,",
			"`UNAVAILABLE` is `network` and invites a retry, `UNIMPLEMENTED` and `INTERNAL` are",
			"`http`, and everything else is `domain` with the status name as the code. Without the",
			"mapping a cancelled call and a failed one look the same, and the user is shown an error",
			"for leaving the screen.",
			"",
			"## `grpc-status` arrives in two places",
			"",
			"In the trailers frame at the end of the body, and — for a call that failed before any",
			"message — in the HTTP headers. Both are read, headers first: a trailers-only response",
			"has no body to find them in, and a reader that only knows one of the two reports a",
			"schema failure for what is an ordinary permission denial.",
			"",
			"## Streaming needs no second protocol",
			"",
			"A server stream is the same framing arriving over time, so `LankaGrpcStreamTransport` is",
			"an `ILankaServerEventTransport` like every other: `eventTypeOf` says which named event a",
			"decoded message is, and a bridge cannot tell it from SSE.",
		],
	},
	{
		kind: "plugin",
		slug: "prefetch",
		short: "prefetch",
		title: "Network priority ladder",
		gist: "SSE > request > route chunk > prefetch — a rule the code enforces.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		// Its own entry: an application that builds its own chunk source never
		// loads the router binding, and the binding names no router.
		entries: [{ name: "router", file: "lanka-router-chunk-source/lankaRouterChunkSource.ts" }],
		socket: "use(plugin) · the instance's observable in-flight counter",
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		contains: [
			"`LankaIntentPrefetch` — short-lived buffer: claim, freshness fences, TTL, eviction",
			"`LankaChunkPreload` — chunk sweeping with its own counter and expirable gates",
			"`LankaDataWarmup` — batched data warm-up with a ceiling on waiting for silence",
		],
		notes: [
			"## The ladder",
			"",
			"```",
			"SSE  >  ordinary request  >  route chunk  >  data warm-up  >  intent buffer",
			"```",
			"",
			"## Three tiers, three counters — not duplication",
			"",
			"The request counter lives in core: there is one send point and the accounting belongs",
			"there. The chunk counter lives here because a chunk is pulled by a dynamic `import()`",
			"and is invisible to the request layer; without it, data warm-up would read the wire as",
			'quiet mid-sweep and "code first, then data" would rest on a head start rather than a gate.',
			"",
			"The intent buffer counts its OWN in-flight requests and SUBTRACTS them from the total.",
			"Without that it would see its own request as foreign traffic after the first warm-up and",
			"stop itself — permanently and silently.",
			"",
			"The tiers also differ by consumer: data warm-up must yield to chunks, the intent buffer",
			"must not. It fires on a confirmed gesture toward a known screen and DISCARDS rather than",
			"defers; letting a speculative background chunk suppress it would trade a certain win for",
			"a guess.",
			"",
			"## Every gate is escapable",
			"",
			"Gates EXPIRE, waiting for silence has a CEILING, and a platform that never reported its",
			"visibility is not believed. An absolute gate switches the service off forever on one",
			"unlucky moment: a pause whose release never arrives, a connection read as slow in the",
			"one second that mattered, a start before the router published its routes — all invisible",
			"in a desktop browser and ordinary inside a mobile client.",
			"",
			"## A buffer, not a cache",
			"",
			"Entries live seconds and are read once, so there is no invalidation bus and no way to",
			"get it wrong. A live event always beats a warmed copy, through domain fences counted by",
			"a COUNTER rather than a list of touched entities: guessing which entry went stale is",
			"exactly the guess that cannot be made safely. A redundant invalidation costs one",
			"ordinary request.",
		],
	},
	{
		kind: "plugin",
		slug: "bootstrap-steps",
		short: "bootstrap-steps",
		title: "Bootstrap pipeline with context",
		gist: "A step receives context, returns it changed, may exit early and redirect.",
		runtime: ["browser", "node", "native"],
		hasTests: true,
		contains: [
			"`createLankaBootstrapPipeline` — a chain of steps with context, early exit and run memory",
			"`lankaBootstrapSteps` — the same pipeline bound to a framework instance's lifetime",
		],
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		socket: "use(plugin)",
		notes: [
			"## Boundary against core's service plan",
			"",
			"Core runs a SET of services: each has a name, priority, sync flag, failure mode and",
			"timeout, and they do not talk to each other. This is a CHAIN: a step reads what the",
			'previous one produced and may say "stop here, send the user there". Core can only',
			'"run or throw", and an early exit cannot be expressed that way — an exception would mean',
			"bootstrap failed, and this is not a failure but a decision.",
			"",
			"So the plugin holds exactly four things core does not: a typed context, early exit, a",
			"redirect target, and run memory (once per session; concurrent calls share one promise).",
			"Concurrency, priorities and phase order stayed in core.",
			"",
			"`optional` and `timeoutMs` exist here TOO, and that is not duplication: the executor is",
			"different (sequential, with context) while the questions the configuration answers are",
			"the same. Different words for one thing would force the reader to remember which of the",
			"two they are in.",
			"",
			"## What is remembered",
			"",
			'Only a COMPLETED run. An early exit means "the user is not signed in"; remembering it',
			"would strand the app on the sign-in screen forever, because the next attempt would",
			"return the same answer without going anywhere. A failure is not remembered for the same",
			"reason.",
		],
	},
	{
		kind: "plugin",
		slug: "devtools",
		short: "devtools",
		title: "Bus and transport inspector",
		gist: "The data is already collected and shown to nobody.",
		runtime: ["browser"],
		hasTests: true,
		contains: [
			"`LankaDevtoolsCollector` — bounded history of events, logs, requests and the scenario register",
			"`renderLankaDevtoolsPanel` — four tabs, a filter, clear and copy; absent outside development",
		],
		devDeps: { "@lankajs/tool-testing": "workspace:^" },
		socket: "LankaLogger sinks · lankaEventBus.addMiddleware · lankaEventBus.addObserver · useRequestMiddleware · inFlight",
		notes: [
			"## A disabled inspector accumulates NOTHING",
			"",
			"Its main property, pinned by its own test. Always-on history is a leak with a user",
			"interface: it looks like diagnostics and behaves as slow memory growth, visible only in",
			"a long session.",
			"",
			"So the inspector has its OWN source, enabled together with it, and its own known buffer",
			"bound. Outside development it subscribes to nothing and returns an empty snapshot.",
			"",
			"## The inspector observes and does not decide",
			"",
			'Its bus middleware always answers `"pass"`. Able to stop delivery, a diagnostic tool',
			'would become a participant, and "disabled the inspector, it started working" would',
			"become a possible sentence.",
			"",
			"## Why `stoppedBy` needed a sixth extension point",
			"",
			"A bus middleware sees only the chain AHEAD of itself, and a diagnostic tool's is the",
			"first one registered — so it could never learn that a later middleware stopped an event.",
			"The field existed and the guide described it; nothing filled it. `lankaEventBus.addObserver`",
			"reports the outcome of a dispatch after the whole chain has run, and cannot decide",
			'anything: a diagnostic tool that could stop an event would make "I disabled the inspector',
			'and it started working" a sentence somebody says.',
			"",
			"## The panel is absent from a production build",
			"",
			"`renderLankaDevtoolsPanel` returns `undefined` before doing any work, so the consumer's",
			"bundler removes its body and everything it references. A panel in production is not a",
			"little extra code — it is an interface that can appear on a user's screen.",
		],
	},
	{
		kind: "tool",
		slug: "di",
		short: "di",
		title: "The consumer contract",
		gist: "The `@lanka_di` alias, scaffolding for six barrels, and a contract check before the build starts — for six bundlers, or for one with no adapter at all.",
		runtime: ["node"],
		hasTests: true,
		entries: [
			{ name: "vite", file: "vite.ts" },
			{ name: "webpack", file: "webpack.ts" },
			{ name: "turbopack", file: "turbopack.ts" },
			{ name: "rollup", file: "rollup.ts" },
			{ name: "esbuild", file: "esbuild.ts" },
			{ name: "metro", file: "metro.ts" },
		],
		// Vite is a peer for its TYPES alone, and an optional one: a webpack
		// consumer installs this package and must not be asked for a bundler they
		// do not use. Webpack is not here at all — the plugin describes the four
		// members of `Compiler` it touches and imports nothing.
		peer: { vite: "^7.3.1" },
		peerOptional: ["vite"],
		devDeps: { vite: "^7.3.1" },
		notes: [
			"## Why the package is not named after a bundler",
			"",
			"The contract is `.lanka_di` — six barrels an application publishes and the framework",
			"reads. Which bundler sets the alias is a detail of the build, and naming the package",
			"after one of them made the other look unsupported.",
			"",
			"The root entry is what no bundler owns: the contract, the scaffolder, the verifier.",
			"`/vite`, `/webpack`, `/turbopack`, `/rollup`, `/esbuild` and `/metro` are thin",
			"adapters over the same three jobs, and `lankaDiSetup` is those three jobs for a",
			"bundler with no adapter at all.",
			"",
			"## Why no bundler is a dependency",
			"",
			"A webpack plugin is an object with `apply`; a Metro adapter is a function of a config",
			"object. Both are described structurally here and import nothing, so a vite consumer is",
			"never asked to install webpack, and a React Native consumer is never asked for vite —",
			"which is an optional peer, for its types alone.",
		],
	},
	{
		kind: "tool",
		slug: "eslint",
		short: "eslint",
		title: "Boundary rules",
		gist: "The framework's main promise — imports go one way — is checked by the framework, not by its consumers.",
		runtime: ["node"],
		hasTests: true,
		peer: { eslint: ">=9" },
		// typescript-eslint is for the fixtures only: `import type` is its syntax, and the
		// rules that skip a type-only import need one to prove it. The peer stays eslint alone.
		devDeps: { eslint: "^9.39.2", "typescript-eslint": "^8.53.1" },
		notes: [
			"## Why the rules live here",
			"",
			"A framework whose main promise is verified by copies of a script inside each consumer",
			"does not verify it at all, and the third consumer gets nothing.",
			"",
			"## Every rule has a FAILING fixture",
			"",
			"A rule without one is a glob that matches nothing: it does not fail, it silently checks",
			"nobody. Fifteen rule blocks once went quiet at once this way, and nothing went red.",
			"",
			"Fixtures are shaped like a CONSUMER, not like the framework: the rules inspect an",
			"application tree, so a fixture built from framework files would prove the wrong thing.",
			"",
			"## The ready-made config is for an application",
			"",
			"`lankaBoundaries` cannot be applied to the framework itself: the `@lanka_di/*` rule",
			"forbids exactly the inversion the framework stands on. Paths in the rules are settings —",
			"a different tree configures them, it does not switch them off.",
		],
	},
	{
		kind: "tool",
		slug: "testing",
		short: "testing",
		title: "Test kit",
		gist: "The only package allowed into core's internals, and therefore the one that justifies sealing them.",
		runtime: ["node"],
		hasTests: true,
		deps: { lanka: "workspace:^" },
		peer: { vitest: "^3.2.4" },
		// Besides the root, four entries are exposed: the setup file is wired by path
		// rather than imported, the host and the alias fixture are taken one at a time
		// so nothing else comes with them, and the bench yardstick is its own entry
		// because a framework-free package benching itself must not pull core in
		// through the root barrel.
		entries: [
			"setupTests",
			"lankaTestHost",
			"vitest",
			"resetLanka",
			"lankaBenchCalibration",
			// Its subpath and its file differ because the unit is TESTED, and the
			// structure canon puts a tested unit in its own folder with its test. The
			// consumer still types `@lankajs/tool-testing/lankaValidatorConformance`.
			{
				name: "lankaValidatorConformance",
				file: "lanka-validator-conformance/lankaValidatorConformance.ts",
			},
			{
				name: "lankaReadCacheConformance",
				file: "lanka-read-cache-conformance/lankaReadCacheConformance.ts",
			},
			{
				name: "lankaStorageAdapterConformance",
				file: "lanka-storage-adapter-conformance/lankaStorageAdapterConformance.ts",
			},
		],
		contains: [
			"`setupTests` — resets the registry, timers, mocks and DOM between tests",
			"`lankaTestHost` — a host for a spec that is not about the host",
			"`createLankaFakeTransport` — one answer, or a route per endpoint with `times` and `delayMs`",
			"`registerLankaFakes` — which double stands for which name, in all four locators",
			"`createLankaEventRecorder`, `createLankaLogRecorder` — what crossed the bus, what was logged",
			"`waitForLankaIdle` — the wire is clear and the work it started has settled",
			"`lankaValidatorConformance` — the assertions every `modules/validators/` package must pass",
			"`lankaStorageAdapterConformance` — the same, for every adapter behind `ILankaStorageAdapter`",
			"`createLankaFakeStorageAdapter` — a storage engine in a `Map`, and the port's second implementation",
		],
		notes: [
			"## Why the kit exists",
			"",
			"Without a public way to start over, tests reach into core's scenario registry directly,",
			"and the absence of an API becomes N call sites that any registry refactor breaks.",
			"",
			"`resetLanka()` creates a NEW instance and DISPOSES the previous one. Both are required:",
			"cleaning leaves behind whatever nobody remembered to clean, and an instance dropped",
			"without disposal keeps ViewModel subscriptions alive — they are declared at module level",
			"and outlive any test, so the second test receives events the first subscribed to.",
			"",
			"`renderWithLanka()` gives a fresh instance on EVERY call. A test that inherits foreign",
			"subscriptions passes or fails depending on its neighbour — the worst kind of unreliable",
			"test, because it goes red where nothing is broken.",
			"",
			'The scenario double returns a REAL unsubscribe. A stub would make the test "the',
			'ViewModel unsubscribes" prove only that a function was called.',
			"",
			"## A helper that waits, rejects",
			"",
			"`waitForLankaIdle` and the event recorder's `waitFor` both fail on their deadline and",
			"name their subject. A helper that resolved late and silently is how a suite fills with",
			"tests that pass without the thing having happened — and those are the tests nobody can",
			"tell apart from the ones that mean something.",
			"",
			"## What the kit does NOT double",
			"",
			"A ViewModel: it is the subject, and what it needs from outside arrives as parameters.",
			"",
			"Storage was on this list until the port moved, and the reason it was here still holds:",
			"this package depends on `lanka` and nothing else, so a double over a MODULE's port would",
			"invert the direction the whole repository points. What changed is the port —",
			"`ILankaStorageAdapter` is declared in `lanka/storage`, and the double stands over core's",
			"interface rather than over `@lankajs/storage`.",
		],
	},
	{
		kind: "tool",
		slug: "skills",
		short: "skills",
		title: "Skill installer",
		gist: "Puts each installed package's agent skill into the project, at the version actually installed.",
		runtime: ["node"],
		hasTests: true,
		bin: { "lanka-skills": "cli" },
		entries: ["cli"],
		contains: [
			"`lanka-skills sync` — copies the skills of the installed lanka packages into the project",
			"`lanka-skills list` — says what would be copied, and from which version",
		],
		notes: [
			"## Why a CLI and not a postinstall",
			"",
			"Writing into a consumer's repository is theirs to ask for. A postinstall that created",
			"files under `.claude/` would do it on every install, in CI and inside a container — and",
			"the first time anybody notices is a diff they did not make.",
			"",
			"## Why this exists beside the plugin marketplace",
			"",
			"A skill installed from git describes the framework's main branch. This one describes the",
			"code in the consumer's `node_modules`, because it is copied out of the tarball they",
			"installed. That is the whole reason for a second transport: a skill teaching a version",
			"the application is not running is worse than no skill, because it is wrong confidently.",
			"",
			"## What it refuses to do",
			"",
			"Overwrite a directory it did not write. Every directory it creates carries a marker file;",
			"one without it belongs to the consumer — hand-written, or from somewhere else — and is",
			"reported rather than replaced. `--force` is the explicit way to say otherwise.",
		],
	},
];

export const byKind = (kind) => PACKAGES.filter((p) => p.kind === kind);
export const pkgName = (p) => KINDS[p.kind].naming(p.short);
export const pkgDir = (p) =>
	p.kind === "core" ? "core" : [KINDS[p.kind].dir, p.family, p.slug].filter(Boolean).join("/");

/** Every declared family directory, as paths: `modules/validators`. */
export const familyDirs = () =>
	FAMILIES.map((f) => `${KINDS[f.kind].dir}/${f.slug}`).sort((a, b) => a.localeCompare(b));

/** Every package directory, which is what "a package root" MEANS. */
export const packageDirs = () => PACKAGES.map(pkgDir).sort((a, b) => a.localeCompare(b));

/** The packages of one family, in registry order. */
export const familyMembers = (slug) => PACKAGES.filter((p) => p.family === slug);
